#!/bin/bash -l
# Queue to use
#PBS -q default
# NAME of job
#PBS -N trial_electrode
# Account resources to use
#PBS -A DBIC
# Resources to reserve
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:25:00
# Send email to this address
#PBS -M Lucy.W.Owen.GR@Dartmouth.edu
# When to send defined here
#PBS -m ea
# Change to job working directory
cd $PBS_O_WORKDIR
##############################
# Enter your code to run below
##############################
python print.py $casenumber $electrode_number 10 10